# Generated by Django 6.1 on 2026-08-16 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Analgesic', 'Analgesic'), ('Antibiotic', 'Antibiotic'), ('Antiseptic', 'Antiseptic'), ('Antiviral', 'Antiviral'), ('Cardiac', 'Cardiac'), ('Dermatological', 'Dermatological'), ('Gastrointestinal', 'Gastrointestinal'), ('Respiratory', 'Respiratory'), ('Supplement', 'Supplement'), ('Other', 'Other')], default='Other', max_length=50)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('stock_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier', models.CharField(max_length=150)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
